(() => {
  const API="https://zztqjwqwyfscwumneak.supabase.co/functions/v1/exam-api", $=id=>document.getElementById(id), text=v=>String(v??""), time=v=>v?new Date(v).toLocaleString("ja-JP"):"—";
  const actionNames={exam_started:"受験開始",exam_submitted:"提出",student_reset:"再受験許可",reset_all:"オールリセット",admin_login:"管理画面ログイン",teacher_created:"教員追加"};
  let token=sessionStorage.getItem("pycbt-admin-token")||"",students=[],resetTarget=null;
  async function call(path,opt={}){const r=await fetch(API+path,{...opt,headers:{"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{})}}),d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||"network_error");e.status=r.status;throw e}return d}
  function cell(row,value,className=""){const td=document.createElement("td");td.textContent=text(value);if(className)td.className=className;row.append(td);return td}
  function emptyRow(body,columns,message){const td=cell(body.insertRow(),message,"empty-cell");td.colSpan=columns}
  const statusLabel=status=>status==="submitted"?"提出済み":"受験中";
  function filteredStudents(){const grade=$("filter-grade").value,classNo=$("filter-class").value,status=$("filter-status").value,query=$("filter-query").value.trim().toLowerCase();return students.filter(s=>(!grade||text(s.grade)===grade)&&(!classNo||text(s.class_no)===classNo)&&(!status||s.status===status)&&(!query||s.student_id.toLowerCase().includes(query)||s.student_name.toLowerCase().includes(query)))}
  function updateSummary(){const submitted=students.filter(s=>s.status==="submitted"),scores=submitted.filter(s=>s.total_score!=null).map(s=>Number(s.total_score)).filter(Number.isFinite);$("count-all").textContent=students.length;$("count-active").textContent=students.filter(s=>s.status==="active").length;$("count-submitted").textContent=submitted.length;$("average-score").textContent=scores.length?`${(scores.reduce((a,b)=>a+b,0)/scores.length).toFixed(1)}点`:"—"}
  function updateClassOptions(){const selected=$("filter-class").value,classes=[...new Set(students.map(s=>Number(s.class_no)))].sort((a,b)=>a-b);$("filter-class").replaceChildren(new Option("すべて",""),...classes.map(n=>new Option(`${n}組`,n)));if(classes.includes(Number(selected)))$("filter-class").value=selected}
  function renderStudents(){const body=$("student-rows"),rows=filteredStudents();body.replaceChildren();if(!rows.length)return emptyRow(body,8,"条件に一致する記録はありません。");rows.forEach(s=>{const row=body.insertRow();cell(row,s.student_id);cell(row,`${s.grade}年 ${s.class_no}組 ${s.attendance}番`);cell(row,s.student_name);cell(row,statusLabel(s.status),`status-${s.status}`);cell(row,s.status==="submitted"&&s.total_score!=null?`${s.total_score} / ${s.max_score??100}`:"—");cell(row,time(s.started_at));cell(row,time(s.submitted_at));const actions=row.insertCell();actions.className="row-actions";if(s.status==="submitted"){const detail=document.createElement("button");detail.textContent="答案";detail.className="secondary small";detail.onclick=()=>showDetail(s.student_id);actions.append(detail)}const reset=document.createElement("button");reset.textContent="再受験";reset.className="danger-outline small";reset.onclick=()=>openReset(s);actions.append(reset)})}
  function renderTeachers(list){const target=$("teacher-list");target.replaceChildren();if(!list.length){const li=document.createElement("li");li.textContent="追加済みの個別アカウントはありません。";return target.append(li)}list.forEach(t=>{const li=document.createElement("li");li.textContent=`${t.display_name}（${t.teacher_id}）`;target.append(li)})}
  function renderAudit(logs){const body=$("audit-rows");body.replaceChildren();if(!logs.length)return emptyRow(body,4,"操作ログはありません。");logs.forEach(log=>{const row=body.insertRow();cell(row,time(log.created_at));cell(row,actionNames[log.action]||log.action);cell(row,log.student_id||"—");cell(row,log.detail||"—")})}
  async function load(){$("student-message").textContent="読み込み中…";try{const [s,t,a]=await Promise.all([call("/v1/admin/students"),call("/v1/admin/teachers"),call("/v1/admin/audit")]);students=s.students;updateClassOptions();updateSummary();renderStudents();renderTeachers(t.teachers);renderAudit(a.logs);$("last-updated").textContent=`更新 ${new Date().toLocaleTimeString("ja-JP")}`;$("student-message").textContent=""}catch(e){if(e.status===401)return logout();$("student-message").textContent="一覧を取得できませんでした。通信を確認して再度お試しください。"}}
  async function showDetail(id){const content=$("detail-content"),heading=document.createElement("h2");heading.textContent="答案を読み込み中…";content.replaceChildren(heading);$("detail-dialog").showModal();try{const {student,result}=await call(`/v1/admin/students/${encodeURIComponent(id)}`);content.replaceChildren();const title=document.createElement("h2");title.textContent=`${student.student_id} ${student.student_name} の答案`;const summary=document.createElement("p");summary.className="detail-summary";summary.textContent=`得点 ${result?.scores?.total?.earned??"—"} / ${result?.scores?.total?.max??"—"}点　知識・技能 ${result?.scores?.knowledge?.earned??"—"}点　思考・判断・表現 ${result?.scores?.thinking?.earned??"—"}点`;const wrap=document.createElement("div"),table=document.createElement("table");wrap.className="table-wrap";table.innerHTML="<thead><tr><th>問題</th><th>分野</th><th>解答</th><th>正誤</th><th>得点</th></tr></thead>";const body=table.createTBody();(result?.questions||[]).forEach(q=>{const row=body.insertRow();cell(row,q.question_id);cell(row,q.domain);cell(row,q.response||"（未回答）");cell(row,q.correct?"○":"×",q.correct?"answer-correct":"answer-wrong");cell(row,`${q.earned} / ${q.points}`)});wrap.append(table);content.append(title,summary,wrap)}catch{const p=document.createElement("p");p.textContent="答案を取得できませんでした。";content.replaceChildren(p)}}
  function openReset(s){resetTarget=s;$("reset-student").textContent=`${s.student_id} ${s.student_name}`;$("reset-reason").value="";$("reset-dialog").showModal();$("reset-reason").focus()}
  function closeReset(){$("reset-dialog").close();resetTarget=null}
  function openResetAll(){$("reset-all-count").textContent=`${students.length}件`;$("reset-all-reason").value="";$("reset-all-confirmation").value="";$("reset-all-dialog").showModal();$("reset-all-reason").focus()}
  function closeResetAll(){$("reset-all-dialog").close()}
  const csvValue=v=>`"${text(v).replaceAll('"','""')}"`;
  async function exportCsv(){const {submissions}=await call("/v1/admin/export"),header=["受験番号","学年","組","出席番号","氏名","開始日時","提出日時","総合得点","総合満点","知識・技能得点","知識・技能満点","思考・判断・表現得点","思考・判断・表現満点","問題ID","分野","観点","形式","解答","正誤","問題配点","得点","variant_group","variant_id","visual_type"],rows=[header];submissions.forEach(s=>{const r=s.result||{},score=r.scores||{},base=[s.student_id,s.grade,s.class_no,s.attendance,s.student_name,s.started_at,s.submitted_at,score.total?.earned,score.total?.max,score.knowledge?.earned,score.knowledge?.max,score.thinking?.earned,score.thinking?.max];(r.questions||[]).forEach(q=>rows.push([...base,q.question_id,q.domain,q.viewpoint,q.format,q.response,q.correct?"正解":"不正解",q.points,q.earned,q.variant_group,q.variant_id,q.visual_type]))});const link=document.createElement("a");link.href=URL.createObjectURL(new Blob(["\ufeff"+rows.map(row=>row.map(csvValue).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}));link.download=`pycbt_答案得点_${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(link.href)}
  function logout(){token="";sessionStorage.removeItem("pycbt-admin-token");location.reload()}
  async function loggedIn(){$("login-panel").hidden=true;$("admin-panel").hidden=false;await load()}
  $("login-form").onsubmit=async e=>{e.preventDefault();$("login-message").textContent="確認中…";try{const d=await call("/v1/admin/login",{method:"POST",body:JSON.stringify({teacher_id:$("login-id").value,password:$("login-password").value})});token=d.token;sessionStorage.setItem("pycbt-admin-token",token);await loggedIn()}catch(error){$("login-message").textContent=error.message==="invalid_credentials"?"IDまたはパスワードを確認してください。":"受験台帳サーバーへ接続できません。学校のネットワーク設定を確認してください。"}};
  $("teacher-form").onsubmit=async e=>{e.preventDefault();try{await call("/v1/admin/teachers",{method:"POST",body:JSON.stringify({teacher_id:$("teacher-id").value,display_name:$("teacher-name").value,password:$("teacher-password").value})});e.target.reset();$("teacher-message").textContent="担当教員を追加しました。";await load()}catch{$("teacher-message").textContent="追加できませんでした。IDの重複や入力条件を確認してください。"}};
  $("reset-form").onsubmit=async e=>{e.preventDefault();if(!resetTarget)return;const button=e.submitter;button.disabled=true;try{await call("/v1/admin/reset",{method:"POST",body:JSON.stringify({student_id:resetTarget.student_id,reason:$("reset-reason").value.trim()})});closeReset();await load()}catch{alert("再受験を許可できませんでした。入力内容と通信状態を確認してください。")}finally{button.disabled=false}};
  $("reset-all-form").onsubmit=async e=>{e.preventDefault();if($("reset-all-confirmation").value.trim()!=="全件削除"){alert("確認欄へ「全件削除」と正確に入力してください。");return}const button=e.submitter;button.disabled=true;try{const result=await call("/v1/admin/reset-all",{method:"POST",body:JSON.stringify({reason:$("reset-all-reason").value.trim(),confirmation:$("reset-all-confirmation").value.trim()})});closeResetAll();await load();alert(`${result.deleted}件の受験記録を削除しました。`)}catch{alert("オールリセットを実行できませんでした。入力内容と通信状態を確認してください。")}finally{button.disabled=false}};
  ["filter-grade","filter-class","filter-status"].forEach(id=>$(id).onchange=renderStudents);$("filter-query").oninput=renderStudents;document.querySelectorAll("[data-close-reset]").forEach(b=>b.onclick=closeReset);document.querySelectorAll("[data-close-reset-all]").forEach(b=>b.onclick=closeResetAll);$("reset-all").onclick=openResetAll;$("refresh").onclick=load;$("export-csv").onclick=()=>exportCsv().catch(()=>alert("CSVを出力できませんでした。"));$("logout").onclick=logout;if(token)loggedIn();
})();
